### ISSUE TITLE
转markdown的时候无法解析富文本中的图像

### ISSUE THREAD

**Issue by bing127** [memspace/zefyr#260]
报错如下：
Invalid argument(s): Cannot handle embed: {type: image, source: file:///storage/emulated/0/Tencent/QQ_Images/-1552448e1a07a21a.jpg}

**Comment by xuanxwz** [comment]
老哥 没有图像的怎么转markdown 啊

**Comment by bing127** [comment]
通过 notusMarkdown.encode(contents)

**Comment by Dorbmon** [comment]
Anything new about this?

**Comment by pheromone** [comment]
@bing127 
什么意思？？通过notusMarkdown.encode(contents)？？？

**Comment by barbecue-pan** [comment]
> @bing127
> 什么意思？？通过notusMarkdown.encode(contents)？？？

这个建议clone 这个仓库 参考他的例子 以及看源码 我当初是这样解决的

**Comment by pheromone** [comment]
@barbecue-pan 
我已经把这个库放在本地引入，toolbar样式和工具部分已经修改了。你的意思是这个不需要借助markdown？
https://github.com/memspace/zefyr/issues/166

**Comment by aboutmydreams** [comment]
感谢，我将多位大佬解决的问题合并入代码然后后放在了仓库，并将 notus 和 zefyr 做了拆分，有需要的可以这样使用
```
dependency_overrides:
  notus:
    git: https://github.com/aboutmydreams/notus.git
  zefyr: 
    git: https://github.com/aboutmydreams/zefyr.git
```
