### ISSUE TITLE
MAC OS Build failed 

### ISSUE THREAD

**Issue by shofi-ishraak** [memspace/zefyr#358]
## Steps to Reproduce

1. Zefyr causing Mac OS desktop build failed . I know mac os support not added yet ... rather then showing a platform  exception  i causing  build failed !

## Logs

```
```

```
```

**Comment by GyuriMajercsik** [comment]
I managed to start Zefyr on MacOS, although, there are many issues. 
To just start on MacOS you should use Zefyr from master:

```
  zefyr:
    git:
      url: https://github.com/memspace/zefyr.git
      path: packages/zefyr

```
