### ISSUE TITLE
The method 'ZefyrView' isn't defined

### ISSUE THREAD

**Issue by webphplove** [memspace/zefyr#64]
When I downloaded zefyr (0.3.0) at pub.flutter-io.cn, I found that the ZefyrView object was undefined. I found that there is no "export 'src/widgets/view.dart';" in the zefyr package. Can you update the latest version?

**Comment by pulyaevskiy** [comment]
If you really need to try latest version of the package you'd need to update your dependency to point to github repo like this:

```yaml
dependencies:
  zefyr:
    git:
      url: https://github.com/memspace/zefyr.git
      path: packages/zefyr
```

Note that `ZefyrView` is still under development and might even be replaced by a different implementation.

There will also be more breaking changes coming in the next two weeks which will land to master branch without prior notice, just an FYI.
